const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const pkgPath = path.join(rootDir, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
const version = pkg.version;

console.log('[Sync Version] Synchronizing version ' + version + ' across all project files...');

// 1. frontend/package.json
const frontPkgPath = path.join(rootDir, 'frontend', 'package.json');
if (fs.existsSync(frontPkgPath)) {
  const frontPkg = JSON.parse(fs.readFileSync(frontPkgPath, 'utf8'));
  if (frontPkg.version !== version) {
    frontPkg.version = version;
    fs.writeFileSync(frontPkgPath, JSON.stringify(frontPkg, null, 2) + '\n');
    console.log('  - Updated frontend/package.json -> ' + version);
  }
}

// 2. oneview.iss
const issPath = path.join(rootDir, 'oneview.iss');
if (fs.existsSync(issPath)) {
  let iss = fs.readFileSync(issPath, 'utf8');
  const updatedIss = iss.replace(/^AppVersion=.*/m, 'AppVersion=' + version);
  if (updatedIss !== iss) {
    fs.writeFileSync(issPath, updatedIss, 'utf8');
    console.log('  - Updated oneview.iss -> ' + version);
  }
}

// 3. src/version.zig
const zigVerPath = path.join(rootDir, 'src', 'version.zig');
const zigContent = '// Auto-generated by scripts/sync-version.js. Do not edit manually.\r\npub const APP_VERSION = "' + version + '";\r\n';
if (!fs.existsSync(zigVerPath) || fs.readFileSync(zigVerPath, 'utf8') !== zigContent) {
  fs.writeFileSync(zigVerPath, zigContent, 'utf8');
  console.log('  - Updated src/version.zig -> ' + version);
}

console.log('[Sync Version] Done.');
